# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzU1OWExZTM1MTYzMzAwYjVjYTM3YTFmZmM2OTM4ZTI4MGVkYjBkZmEwMDU2OWFmZDgwZThhNmYxZDIxZDEyZmJmOTQzOTA3NjBkOGY2ZWQ0MWY2OTkyZWIyNGNmZjBhNGZjMTk5MWQ3NDNmNWExODk5NjU0ZDAyOWM4ZjFmY2Q=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
